apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-acr-pod
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-acr-pod
    spec:
      containers:
      - name: nginx
        image: openhackacsreg.azurecr.io/nginxminecraftstats:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: openhackacsreg.azurecr.io
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-acr-pod