apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: default