apiVersion: apps/v1beta1
kind: StatefulSet #Deployment
metadata:
  name: azure-minecraft-ps
spec:
  replicas: 3
  serviceName: "azure-minecraft"
  template:
    metadata:
      labels:
        app: azure-minecraft-ps
    spec:
      containers:
      - name: azure-minecraft
        image: openhack/minecraft-server:1.0
        volumeMounts:
        - mountPath: "/data"
          name: data
        ports:
        - containerPort: 25565
          name: connport
        - containerPort: 25575
          name: remoteport
        env:
        - name: EULA
          value: "TRUE"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "default"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: azure-minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: connport
  - port: 25575
    name: remoteport
  selector:
    app: azure-minecraft-ps