apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-minecraft-ps
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: azure-minecraft-ps
    spec:
      containers:
      - name: azure-minecraft
        image: openhack/minecraft-server:1.0
        volumeMounts:
        - mountPath: "/data"
          name: azurefileshare
        ports:
        - containerPort: 25565
          name: connport
        - containerPort: 25575
          name: remoteport
        env:
        - name: EULA
          value: "TRUE"
      volumes:
        - name: azurefileshare
          persistentVolumeClaim:
            claimName: dynamic-persistence-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: azure-minecraft
spec:
  type: LoadBalancer
  ports:
  - port: 25565
    name: connport
  - port: 25575
    name: remoteport
  selector:
    app: azure-minecraft-ps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-persistence-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 7Gi